### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [shawnpringle/separatorsafterdecimal#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.0.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary qsdn -w /tmp/ext qsdn==0.0.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting qsdn==0.0.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/dea/48f5fbc51af0d/qsdn-0.0.0.tar.gz (15 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ujjncq6u/qsdn/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ujjncq6u/qsdn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ujjncq6u/qsdn/pip-egg-info
         cwd: /tmp/pip-wheel-ujjncq6u/qsdn/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ujjncq6u/qsdn/setup.py", line 3, in <module>
        with open("doc/build/text/index.txt", "r", encoding='utf-8') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'doc/build/text/index.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by shawnpringle** [comment]
Thank you, thatch.  I will look into this.

**Comment by shawnpringle** [comment]
The standard "pip3 install qsdn" works fine.  You're free to make a PR.

**Comment by thatch** [comment]
Some companies and distros want to compile everything from source, so pass `--no-binary :all:`, for example https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/vpip.py#L311

If your sdist is broken like this, some people are less likely to use it.  If that's not a problem for you, feel free to close as wontfix.  (I submitted PRs to fix hundreds of these that were easy, but that file isn't in the source tree, it's generated by the doc build.)

**Comment by MrBigBanks** [comment]
LICENSE

**Comment by MrBigBanks** [comment]
LICENSE
